### ISSUE TITLE
gngeo_engine.p2control KeyError

### ISSUE THREAD

**Issue by prim** [imamhs/Shopne-Arcade#1]
When I try to use the master version, python3 reports the following error.

```
Traceback (most recent call last):
  File "/home/hcjn0770/geo/Shopne-Arcade-master/Shopne.py", line 1484, in <module>
    main(gngeo_status)
  File "/home/hcjn0770/geo/Shopne-Arcade-master/Shopne.py", line 1369, in main
    load_settings()
  File "/home/hcjn0770/geo/Shopne-Arcade-master/Shopne.py", line 1252, in load_settings
    gngeo_engine.p2control = 'A=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[0].get()] + ',B=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[1].get()] + ',C=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[2].get()] + ',D=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[3].get()] + ',LEFT=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[4].get()] + ',RIGHT=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[5].get()] + ',UP=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[6].get()] + ',DOWN=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[7].get()] + ',START=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[8].get()] + ',COIN=' + GNGEO_GAMEPAD1_KEYCODES[shopne_variables.player2_button_selections[9].get()]
KeyError: 'Start'
```

**Comment by imamhs** [comment]
Hi, thank you a lot for checking and pointing out!

The error can be resolved by the deleting the files inside the "settings" folder so fresh settings files are created. Also, it is good idea to implement some checks to avoid this crash, which I will into it later.

In the meantime please checkout the distribution package (version 1.9) from https://shopnearcade.blogspot.com/p/get-it.html. It has the frontend (Shopne) and also gngeo emulator packaged together to run NeoGeo roms. In the presence of gngeo emulator Shopne would allow to open the different settings windows.

Cheers!
